import { CheckCircle2, ExternalLink, Link2 } from "lucide-react";
import { PendingSubmitButton } from "@/components/ui/pending-submit-button";
import { getTeamPortalData, submissionLabels, submissionTypes } from "@/lib/repositories/team-repository";
import { requireTeamSession } from "@/lib/require-team-session";

export default async function TeamSubmissionsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const data = await getTeamPortalData(await requireTeamSession());
  if (!data) return null;
  const params = await searchParams;
  const byType = new Map(data.submissions.map((submission) => [submission.type, submission]));
  return <div className="space-y-5">
    <div><p className="text-xs font-semibold text-blue-700">Project resources</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Submissions</h1><p className="mt-1 text-sm leading-6 text-zinc-500">Keep the links judges need in one place. You can safely update them until evaluation.</p></div>
    {params.status === "saved" ? <p className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-700"><CheckCircle2 className="size-4" /> Submissions saved successfully.</p> : params.status === "invalid" ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">Enter valid http:// or https:// links.</p> : null}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_260px]"><form action="/team/submissions/save" method="post" className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3.5 sm:px-5"><h2 className="text-sm font-semibold text-zinc-900">Project links</h2><p className="mt-1 text-xs text-zinc-500">Blank fields are treated as not submitted.</p></div><div className="grid gap-4 p-4 sm:grid-cols-2 sm:p-5">{submissionTypes.map((type) => { const existing = byType.get(type); return <label key={type} className="group block text-xs font-medium text-zinc-700"><span className="flex items-center justify-between gap-2"><span>{submissionLabels[type]}</span>{existing ? <span className="flex items-center gap-1 text-[10px] font-semibold text-emerald-600"><CheckCircle2 className="size-3" /> Added</span> : null}</span><div className="relative mt-2"><Link2 className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-zinc-400" /><input name={type} type="url" inputMode="url" defaultValue={existing?.url ?? ""} placeholder="https://" maxLength={2048} className="h-11 w-full rounded-lg border border-zinc-300 pl-9 pr-3 text-sm font-normal outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div></label>; })}</div><div className="flex items-center justify-between gap-3 border-t border-zinc-100 bg-zinc-50/50 px-4 py-3 sm:px-5"><p className="text-xs text-zinc-500">{data.submissions.length} of {submissionTypes.length} linked</p><PendingSubmitButton pendingLabel="Saving links…" className="h-10 rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white hover:bg-zinc-800">Save submissions</PendingSubmitButton></div></form>
      <aside className="space-y-3"><div className="rounded-xl border border-zinc-200 bg-white p-4"><p className="text-xs font-semibold text-zinc-500">Submission readiness</p><p className="mt-2 text-3xl font-semibold tabular-nums text-zinc-950">{Math.round(data.submissions.length / submissionTypes.length * 100)}%</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${data.submissions.length / submissionTypes.length * 100}%` }} /></div></div><div className="rounded-xl border border-blue-200 bg-blue-50/60 p-4"><p className="text-xs font-semibold text-blue-700">Judge access</p><p className="mt-2 text-sm leading-6 text-blue-950/70">These links appear directly on your team’s judge screen.</p><ExternalLink className="mt-3 size-4 text-blue-600" /></div></aside>
    </div>
  </div>;
}
