import { Mail, Send } from "lucide-react";
import { getTeamLeadMailMerge } from "@/lib/repositories/operations-repository";

export const metadata = { title: "Team communications" };

export default async function TeamCommunicationsPage({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) {
  const rows = await getTeamLeadMailMerge();
  const recipients = rows.filter((row) => row.email && row.accessCode).length;
  const missing = rows.length - recipients;
  const params = await searchParams;
  return <div className="max-w-3xl space-y-5"><header><p className="text-xs font-medium text-blue-700">Super-admin tools</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight text-zinc-950"><Mail className="size-5 text-zinc-500" /> Team communications</h1><p className="mt-1 text-sm leading-6 text-zinc-500">Send each team lead their student portal URL, private access code, and feedback form link. Judge feedback remains separate from this student survey.</p></header>{params.sent ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Messages sent successfully.</div> : null}{params.error ? <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{params.error}</div> : null}<section className="rounded-xl border border-zinc-200 bg-white p-5"><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-zinc-500">Teams</p><p className="mt-1 text-2xl font-semibold tabular-nums">{rows.length}</p></div><div><p className="text-xs text-zinc-500">Ready to email</p><p className="mt-1 text-2xl font-semibold tabular-nums text-emerald-700">{recipients}</p></div><div><p className="text-xs text-zinc-500">Missing email/code</p><p className="mt-1 text-2xl font-semibold tabular-nums text-amber-700">{missing}</p></div></div><div className="mt-5 border-t border-zinc-100 pt-4"><p className="text-xs leading-5 text-zinc-500">Only team-member email addresses stored in the database are used. The sender and Brevo API key stay server-side. Sending again will deliver another copy.</p><form action="/admin/communications/send" method="post" className="mt-4"><button type="submit" disabled={!recipients} className="inline-flex h-11 items-center gap-2 rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white hover:bg-zinc-800 disabled:cursor-not-allowed disabled:bg-zinc-300"><Send className="size-4" /> Send portal details to {recipients} team leads</button></form></div></section></div>;
}
