import { CalendarClock, CircleDashed, UserRound, CheckCircle2 } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { ReviewResetControl } from "@/components/admin/review-reset-control";
import { formatDateTime, formatTime } from "@/lib/format";
import type { Judge, Review, ReviewRound, Rubric } from "@/types/domain";

export function ReviewCard({ review, round, rubric, judge, completedByJudge, canReset = false }: { review: Review; round: ReviewRound; rubric: Rubric; judge: Judge; completedByJudge?: Judge | null; canReset?: boolean }) {
  const total = review.scores.reduce((sum, item) => sum + item.score, 0);
  const maximum = rubric.criteria.reduce((sum, item) => sum + item.maxScore, 0);
  const scoreMap = new Map(review.scores.map((item) => [item.criterionId, item.score]));
  return (
    <article className="overflow-hidden rounded-xl border border-zinc-200 bg-white">
      <header className="flex flex-col gap-3 border-b border-zinc-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="font-mono text-[11px] font-semibold text-blue-700">R{round.number}</span><h3 className="text-sm font-semibold text-zinc-950">{round.name}</h3></div><div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-zinc-500"><span className="flex items-center gap-1"><UserRound className="size-3" />{judge.name}</span>{review.startedAt ? <span className="flex items-center gap-1"><CalendarClock className="size-3" />Started {formatTime(review.startedAt)}</span> : null}{completedByJudge && review.status === "completed" ? <span className="flex items-center gap-1"><CheckCircle2 className="size-3 text-emerald-600" />Reviewed by: {completedByJudge.name} {completedByJudge.role ? `(${completedByJudge.role === "external" ? "External" : "Internal"})` : ""}</span> : null}</div></div><div className="flex flex-wrap items-center gap-3"><StatusBadge status={review.status} />{review.status === "completed" ? <div className="border-l border-zinc-200 pl-3 text-right"><span className="text-lg font-semibold tabular-nums text-zinc-950">{total}</span><span className="text-xs text-zinc-400"> / {maximum}</span></div> : null}{canReset && review.status !== "pending" ? <ReviewResetControl reviewId={review.id} teamId={review.teamId} roundNumber={round.number} /> : null}</div></header>
      {review.status === "completed" ? <div><div className="grid divide-y divide-zinc-100 border-b border-zinc-200 sm:grid-cols-5 sm:divide-x sm:divide-y-0">{rubric.criteria.map((criterion) => <div className="px-4 py-3.5" key={criterion.id}><p className="min-h-8 text-[11px] leading-4 text-zinc-500">{criterion.label}</p><p className="mt-1 text-sm font-semibold tabular-nums text-zinc-900">{scoreMap.get(criterion.id)} <span className="font-normal text-zinc-400">/ {criterion.maxScore}</span></p></div>)}</div><div className="grid gap-5 px-5 py-4 md:grid-cols-2"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-400">Remarks</p><p className="mt-1.5 text-xs leading-5 text-zinc-700">{review.remarks}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-400">Improvements</p><p className="mt-1.5 text-xs leading-5 text-zinc-700">{review.improvements}</p></div></div><footer className="border-t border-zinc-100 bg-zinc-50/60 px-5 py-2.5 text-[11px] text-zinc-500">Submitted {formatDateTime(review.submittedAt)}</footer></div> : null}
      {review.status === "in_progress" ? <div className="flex gap-3 px-5 py-6"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-amber-200 bg-amber-50"><CircleDashed className="size-4 text-amber-600" /></div><div><p className="text-sm font-medium text-zinc-900">Evaluation is currently underway</p><p className="mt-1 text-xs leading-5 text-zinc-500">Scores and comments will appear here after the judge submits this review. Started {formatDateTime(review.startedAt)}.</p></div></div> : null}
      {review.status === "pending" ? <div className="flex gap-3 px-5 py-6"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-zinc-50"><CircleDashed className="size-4 text-zinc-400" /></div><div><p className="text-sm font-medium text-zinc-700">Review not started</p><p className="mt-1 text-xs leading-5 text-zinc-500">This round is waiting for the team and assigned judge. No scores have been recorded.</p></div></div> : null}
      {review.status === "absent" ? <div className="flex gap-3 px-5 py-6"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-red-200 bg-red-50"><CircleDashed className="size-4 text-red-600" /></div><div><p className="text-sm font-medium text-red-800">Team marked absent</p><p className="mt-1 text-xs leading-5 text-zinc-500">No marks were recorded for this review. It remains incomplete and can be evaluated later by the assigned judge.</p></div></div> : null}
    </article>
  );
}
