import { IssueCategory } from "@/generated/prisma/client";
import { ChevronDown, CircleHelp, MessageSquareReply, Plus } from "lucide-react";
import { IssueStatusBadge } from "@/components/team/issue-status-badge";
import { PendingSubmitButton } from "@/components/ui/pending-submit-button";
import { formatDateTime } from "@/lib/format";
import { getTeamPortalData } from "@/lib/repositories/team-repository";
import { requireTeamSession } from "@/lib/require-team-session";

export default async function TeamIssuesPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const data = await getTeamPortalData(await requireTeamSession());
  if (!data) return null;
  const params = await searchParams;
  const activeCount = data.issues.filter((issue) => issue.status === "OPEN" || issue.status === "IN_PROGRESS").length;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-blue-700">Help desk</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Issues & support</h1><p className="mt-1 text-sm leading-6 text-zinc-500">Report operational problems and follow faculty responses.</p></div><div className="flex items-center gap-2 text-xs text-zinc-500"><span className="size-2 rounded-full bg-amber-500" /> {activeCount} active</div></div>
    {params.status === "created" ? <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-700">Issue submitted. Faculty can now see it.</p> : params.status === "invalid" ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">Check the issue details and try again.</p> : null}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
      <form action="/team/issues/create" method="post" className="h-fit space-y-4 rounded-xl border border-zinc-200 bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-lg border border-zinc-200 bg-zinc-50"><Plus className="size-4 text-zinc-600" /></div><div><h2 className="text-sm font-semibold text-zinc-900">Report an issue</h2><p className="text-xs text-zinc-500">Be specific so faculty can respond quickly.</p></div></div><label className="block text-xs font-medium text-zinc-700">Category<select name="category" className="mt-2 h-11 w-full rounded-lg border border-zinc-300 px-3 text-sm font-normal outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100">{Object.values(IssueCategory).map((value) => <option key={value}>{value.replace("_", " ")}</option>)}</select></label><label className="block text-xs font-medium text-zinc-700">Title<input name="title" required minLength={4} maxLength={120} placeholder="Brief summary" className="mt-2 h-11 w-full rounded-lg border border-zinc-300 px-3 text-sm font-normal outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label><label className="block text-xs font-medium text-zinc-700">Description<textarea name="description" required minLength={10} maxLength={3000} rows={5} placeholder="What happened, and what do you need?" className="mt-2 w-full rounded-lg border border-zinc-300 p-3 text-sm font-normal leading-6 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label><PendingSubmitButton pendingLabel="Submitting issue…" className="h-11 w-full rounded-lg bg-zinc-950 text-sm font-semibold text-white hover:bg-zinc-800">Submit issue</PendingSubmitButton></form>
      <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold text-zinc-900">Your reports</h2><span className="text-xs text-zinc-500">{data.issues.length} total</span></div><div className="space-y-3">{data.issues.map((issue) => <details key={issue.id} className="group overflow-hidden rounded-xl border border-zinc-200 bg-white transition-all duration-200 open:border-zinc-300 open:shadow-sm"><summary className="flex cursor-pointer list-none items-start gap-3 p-4 sm:p-5"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-zinc-50"><CircleHelp className="size-4 text-zinc-500" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-zinc-900">{issue.title}</p>{issue.adminResponse ? <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-blue-700"><span className="size-1.5 rounded-full bg-red-500" /> Faculty replied</span> : null}</div><p className="mt-1 text-xs text-zinc-500">{issue.category.replace("_", " ")} · Updated {formatDateTime(issue.updatedAt)}</p></div><IssueStatusBadge status={issue.status} /><ChevronDown className="mt-1 size-4 shrink-0 text-zinc-400 transition-transform duration-200 group-open:rotate-180" /></summary><div className="space-y-4 border-t border-zinc-100 bg-zinc-50/40 p-4 text-sm leading-6 text-zinc-600 sm:p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-400">Your report</p><p className="mt-1">{issue.description}</p></div>{issue.adminResponse ? <div className="rounded-lg border border-blue-100 bg-blue-50 p-3.5"><p className="flex items-center gap-1.5 text-xs font-semibold text-blue-700"><MessageSquareReply className="size-3.5" /> Faculty response</p><p className="mt-1.5 text-blue-950/75">{issue.adminResponse}</p></div> : <p className="text-xs text-zinc-500">No faculty response yet.</p>}{issue.resolvedAt ? <p className="text-xs text-emerald-700">Resolved {formatDateTime(issue.resolvedAt)}</p> : null}</div></details>)}{!data.issues.length ? <div className="rounded-xl border border-dashed border-zinc-300 bg-white p-8 text-center"><CircleHelp className="mx-auto size-5 text-zinc-400" /><p className="mt-2 text-sm font-medium text-zinc-700">No issues reported</p><p className="mt-1 text-xs text-zinc-500">Everything looks clear.</p></div> : null}</div></section>
    </div>
  </div>;
}
