import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bell, ChevronDown, MapPin, Palette, Phone, ShieldAlert, UserRound, X } from "lucide-react";
import { formatDateTime } from "@/lib/format";
import { ProgressBar } from "@/components/ui/progress-bar";
import { StatusBadge } from "@/components/ui/status-badge";
import { TeamQrScanner } from "@/components/judge/team-qr-scanner";
import { getJudgeDashboard } from "@/lib/repositories/judge-repository";
import { requireJudgeSession } from "@/lib/require-judge-session";

export const metadata: Metadata = { title: "Judge teams" };

export default async function JudgeHomePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireJudgeSession();
  const [data, params] = await Promise.all([getJudgeDashboard(session), searchParams]);
  if (!data) return null;
  const denied = params.scanError === "wrong-venue";
  return <div className="space-y-5">
    {denied ? <div role="alert" className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-amber-700" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">That team is not assigned to you</p><p className="mt-1 text-xs leading-5 text-amber-800">You can evaluate teams in {data.venues.map((venue) => `${venue.name} · ${venue.roomNumber}`).join(", ")}.</p></div><Link href="/judge" aria-label="Dismiss assignment warning" className="grid size-8 shrink-0 place-items-center rounded-lg text-amber-700 hover:bg-amber-100"><X className="size-4" /></Link></div> : null}
    <TeamQrScanner />
    <section className="rounded-xl border border-zinc-200 bg-white p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">Judge workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-zinc-950">{data.identity.judgeName}</h1><p className="mt-1 text-sm text-zinc-500">{data.venues.length === 1 ? "Assigned venue" : `${data.venues.length} assigned venues`} · {data.teams.length} teams</p><div className="mt-4 flex flex-wrap gap-2 border-t border-zinc-100 pt-4">{data.venues.map((venue) => <span key={venue.id} className="inline-flex items-center gap-1.5 rounded-md border border-zinc-200 bg-zinc-50 px-2.5 py-1.5 text-xs font-medium text-zinc-700"><MapPin className="size-3.5 text-zinc-500" /> {venue.name} · {venue.roomNumber}</span>)}</div></section>
    <details className="group overflow-hidden rounded-xl border border-zinc-200 bg-white"><summary className="flex min-h-14 cursor-pointer list-none items-center gap-3 px-4 py-3"><MapPin className="size-4 text-zinc-500" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-zinc-900">Venue information & contacts</p><p className="mt-0.5 truncate text-xs text-zinc-500">All your assigned evaluation rooms</p></div><ChevronDown className="size-4 text-zinc-400 transition-transform duration-200 group-open:rotate-180" /></summary><div className="divide-y divide-zinc-100 border-t border-zinc-100 bg-zinc-50/50">{data.venues.map((venue) => <div key={venue.id} className="space-y-3 px-4 py-4"><div><p className="text-sm font-semibold text-zinc-900">{venue.name} · {venue.roomNumber}</p><p className="mt-1 text-xs text-zinc-500">{venue.location ?? venue.roomNumber} · {venue.problemRange}</p></div><p className="flex items-center gap-1.5 text-xs text-zinc-600"><Palette className="size-3.5 text-zinc-400" /> {venue.theme ?? "Theme not assigned"}</p><div><p className="text-xs font-medium text-zinc-500">Judges</p>{venue.judges.map((judge) => <p key={`${venue.id}-${judge.id}-${judge.role}`} className="mt-1 flex items-center gap-1.5 text-xs text-zinc-700"><UserRound className="size-3.5 text-zinc-400" /> {judge.name}{judge.phone ? <a href={`tel:${judge.phone}`} className="text-blue-700"> · {judge.phone}</a> : null}</p>)}</div>{venue.coordinators.length ? <div><p className="text-xs font-medium text-zinc-500">Faculty coordinator</p>{venue.coordinators.map((person) => <p key={person.id} className="mt-1 flex items-center gap-1.5 text-xs text-zinc-700"><Phone className="size-3.5 text-zinc-400" /> {person.name}{person.phone ? <a href={`tel:${person.phone}`} className="text-blue-700"> · {person.phone}</a> : null}</p>)}</div> : null}</div>)}</div></details>
    {data.announcements.length ? <section aria-labelledby="judge-announcements"><div className="mb-2 flex items-center justify-between"><h2 id="judge-announcements" className="flex items-center gap-2 text-sm font-semibold text-zinc-900"><Bell className="size-4 text-zinc-500" /> Announcements</h2><span className="text-xs text-zinc-500">{data.announcements.length} active</span></div><div className="space-y-2">{data.announcements.map((item, index) => <details key={item.id} open={index === 0} className="group overflow-hidden rounded-xl border border-zinc-200 bg-white"><summary className="flex min-h-14 cursor-pointer list-none items-center gap-3 px-4 py-3"><span className="size-2 rounded-full bg-blue-600" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-zinc-900">{item.title}</p><p className="mt-0.5 text-[11px] text-zinc-400">{formatDateTime(item.publishedAt)}</p></div><ChevronDown className="size-4 text-zinc-400 transition-transform duration-200 group-open:rotate-180" /></summary><p className="border-t border-zinc-100 bg-zinc-50/50 px-4 py-3 text-sm leading-6 text-zinc-600">{item.message}</p></details>)}</div></section> : null}
    <section><h2 className="mb-2 text-sm font-semibold text-zinc-900">Review progress across assigned venues</h2><div className="divide-y divide-zinc-100 rounded-xl border border-zinc-200 bg-white">{data.rounds.map((round) => <div key={round.id} className="p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium text-zinc-900">Review {round.number}</p><p className="mt-0.5 text-xs text-zinc-500">{round.completed} / {round.total} completed{round.inProgress ? ` · ${round.inProgress} in progress` : ""}</p></div><span className="text-xs font-semibold tabular-nums text-zinc-600">{round.total ? Math.round(round.completed / round.total * 100) : 0}%</span></div><ProgressBar value={round.total ? round.completed / round.total * 100 : 0} className="mt-3" /></div>)}</div></section>
    <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold text-zinc-900">Assigned teams</h2><span className="text-xs text-zinc-500">{data.teams.length} teams</span></div><div className="divide-y divide-zinc-100 rounded-xl border border-zinc-200 bg-white">{data.teams.map((team) => <Link key={team.id} href={`/judge/teams/${team.id}`} className="group block p-4 transition-colors hover:bg-zinc-50 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500"><div className="flex items-start gap-3"><span className="mt-0.5 rounded-md border border-zinc-200 bg-zinc-50 px-2 py-1 font-mono text-xs font-semibold text-zinc-700">{team.code}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-zinc-950">{team.name}</p><p className="mt-1 text-[11px] font-medium text-zinc-500">{team.venueName} · {team.roomNumber}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{team.problemCode} · {team.problemTitle}</p></div><ArrowRight className="mt-1 size-4 shrink-0 text-zinc-300 transition-transform group-hover:translate-x-0.5 group-hover:text-zinc-600" /></div><div className="mt-3 flex flex-wrap gap-1.5">{team.reviews.map((review) => <div key={review.roundId} className="flex items-center gap-1"><span className="text-[10px] font-semibold text-zinc-400">R{review.roundNumber}</span><StatusBadge status={review.status} compact /></div>)}</div></Link>)}</div></section>
  </div>;
}
