import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { ADMIN_SESSION_COOKIE, verifySuperAdminSessionToken } from "@/lib/admin-auth";
import { getAdminManagementData } from "@/lib/repositories/admin-management-repository";

const field = "mt-1 h-10 w-full rounded-lg border border-zinc-300 px-3 text-sm";

export default async function AdminManagePage({ searchParams }: { searchParams: Promise<{ team?: string; delete?: string }> }) {
  const cookieStore = await cookies();
  if (!(await verifySuperAdminSessionToken(cookieStore.get(ADMIN_SESSION_COOKIE)?.value))) redirect("/admin");
  const [data, params] = await Promise.all([getAdminManagementData(), searchParams]);
  const teamMessage = params.team === "created" ? { text: "Team added successfully.", tone: "success" } : params.team === "duplicate" ? { text: "A team with that Team ID already exists. Use a different Team ID or update the existing team.", tone: "error" } : params.team === "invalid" ? { text: "Check the required team fields and selected venue, then try again.", tone: "error" } : params.team === "unavailable" ? { text: "The team could not be added right now. Please try again.", tone: "error" } : null;
  const deleteMessage = params.delete === "deleted" ? { text: "Team deleted. Other Team IDs and access codes were not changed.", tone: "success" } : params.delete ? { text: "Team was not deleted. Type the selected Team ID exactly to confirm.", tone: "error" } : null;

  return <div className="space-y-6">
    <div><p className="text-xs font-medium text-blue-700">Event setup</p><h1 className="mt-1 text-2xl font-semibold">Manage event data</h1><p className="mt-1 text-sm text-zinc-500">Add venues, teams, and judges. Reassign a venue judge without deleting the existing assignment.</p></div>
    {teamMessage ? <div role={teamMessage.tone === "error" ? "alert" : "status"} className={`rounded-lg border px-4 py-3 text-sm ${teamMessage.tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`}>{teamMessage.text}</div> : null}
    {deleteMessage ? <div role={deleteMessage.tone === "error" ? "alert" : "status"} className={`rounded-lg border px-4 py-3 text-sm ${deleteMessage.tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`}>{deleteMessage.text}</div> : null}
    <div className="grid gap-5 xl:grid-cols-2">
      <form action="/admin/manage/venues" method="post" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Add venue</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Code<input name="code" required className={field} /></label><label className="text-xs font-medium">Venue name<input name="name" required className={field} /></label><label className="text-xs font-medium">Room<input name="roomNumber" required className={field} /></label><label className="text-xs font-medium">Building<input name="building" className={field} /></label><label className="text-xs font-medium sm:col-span-2">Theme<input name="theme" className={field} /></label></div><button className="mt-4 h-10 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white">Add venue</button></form>
      <form action="/admin/manage/teams" method="post" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Add team</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Venue<select name="venueId" required className={field}>{data.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name} · {venue.roomNumber}</option>)}</select></label><label className="text-xs font-medium">Team code<input name="teamCode" required maxLength={64} className={field} /></label><label className="text-xs font-medium sm:col-span-2">Team name<input name="teamName" required maxLength={160} className={field} /></label><label className="text-xs font-medium">Problem code<input name="problemCode" required maxLength={64} className={field} /></label><label className="text-xs font-medium">Problem title<input name="problemTitle" required maxLength={500} className={field} /></label></div><button className="mt-4 h-10 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white">Add team</button></form>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <form action="/admin/manage/judges" method="post" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Add judge</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Name<input name="name" required className={field} /></label><label className="text-xs font-medium">Phone<input name="phone" required className={field} /></label><label className="text-xs font-medium">Password<input name="password" type="password" required minLength={6} className={field} /></label><label className="text-xs font-medium">Venue<select name="venueId" required className={field}>{data.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name} · {venue.roomNumber}</option>)}</select></label><label className="text-xs font-medium">Role<select name="role" className={field}><option value="EXTERNAL">External</option><option value="INTERNAL">Internal</option></select></label></div><button className="mt-4 h-10 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white">Add judge</button></form>
      <form action="/admin/manage/assignments" method="post" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Assign or change venue judge</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Venue<select name="venueId" required className={field}>{data.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name} · {venue.roomNumber}</option>)}</select></label><label className="text-xs font-medium">Judge<select name="judgeId" required className={field}>{data.judges.map((judge) => <option key={judge.id} value={judge.id}>{judge.name}</option>)}</select></label><label className="text-xs font-medium">Role<select name="role" className={field}><option value="EXTERNAL">External</option><option value="INTERNAL">Internal</option></select></label><label className="flex items-end gap-2 pb-2 text-sm"><input name="primary" type="checkbox" /> Make primary judge</label></div><button className="mt-4 h-10 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white">Save assignment</button></form>
    </div>
    <form action="/admin/manage/teams/delete" method="post" className="rounded-xl border border-red-200 bg-red-50/40 p-5"><h2 className="text-sm font-semibold text-red-950">Delete team</h2><p className="mt-1 text-xs leading-5 text-red-800">This permanently removes only the selected team and its dependent reviews/submissions. It does not renumber, alter or invalidate any other team.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs font-medium text-zinc-700 sm:col-span-2">Team<select name="teamId" required className={field}>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.teamCode} · {team.teamName} · {team.venue.name}</option>)}</select></label><label className="text-xs font-medium text-zinc-700">Type Team ID to confirm<input name="confirmation" required placeholder="e.g. AR-01" className={field} /></label></div><button className="mt-4 h-10 rounded-lg bg-red-700 px-4 text-sm font-medium text-white hover:bg-red-800">Delete team permanently</button></form>
  </div>;
}
