import type { Metadata } from "next";
import Link from "next/link";
import { ChartColumn, LockKeyhole } from "lucide-react";
import { getProblemStatementAnalytics } from "@/lib/repositories/problem-analytics-repository";

export const metadata: Metadata = { title: "Problem statement analytics", robots: { index: false, follow: false } };
const number = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 });
const score = (value: number | null) => value === null ? "—" : number.format(value);

export default async function ProblemAnalyticsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const data = await getProblemStatementAnalytics(typeof params.round === "string" ? params.round : undefined);
  const teamCount = data.rows.reduce((total, row) => total + row.teamCount, 0);
  const included = data.rows.reduce((total, row) => total + row.sampleSize, 0);
  return <div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium text-blue-700">Evaluation insights</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight"><ChartColumn className="size-5 text-zinc-500" /> Problem statement analytics</h1><p className="mt-1 text-sm text-zinc-500">Compare scores and review progress across every assigned problem.</p></div><span className="inline-flex items-center gap-1.5 rounded-md border border-zinc-200 bg-white px-2.5 py-1.5 text-xs text-zinc-600"><LockKeyhole className="size-3.5" /> Faculty only</span></header>
    <dl className="grid grid-cols-3 divide-x divide-zinc-200 rounded-xl border border-zinc-200 bg-white">
      <div className="p-4"><dt className="text-xs text-zinc-500">Problem statements</dt><dd className="mt-1 text-xl font-semibold">{data.rows.length}</dd></div>
      <div className="p-4"><dt className="text-xs text-zinc-500">Participating teams</dt><dd className="mt-1 text-xl font-semibold">{teamCount}</dd></div>
      <div className="p-4"><dt className="text-xs text-zinc-500">Teams in score sample</dt><dd className="mt-1 text-xl font-semibold">{included}<span className="text-sm font-normal text-zinc-400"> / {teamCount}</span></dd></div>
    </dl>
    <form action="/admin/problem-statements" className="flex flex-wrap items-end gap-3 rounded-xl border border-zinc-200 bg-white p-4"><label className="min-w-56 flex-1 text-xs font-medium text-zinc-600">Compare scores for<select name="round" defaultValue={data.selectedRoundId} className="mt-1.5 h-10 w-full rounded-lg border border-zinc-300 bg-white px-3 text-sm focus-visible:outline-2 focus-visible:outline-blue-600"><option value="">Overall · fully evaluated teams</option>{data.rounds.map((round) => <option key={round.id} value={round.id}>Review {round.number} · {round.name}</option>)}</select></label><button className="h-10 rounded-lg bg-zinc-950 px-4 text-xs font-semibold text-white hover:bg-zinc-800">Apply</button></form>
    <div className="rounded-lg border border-blue-200 bg-blue-50/50 p-3 text-xs leading-5 text-blue-950"><p className="font-semibold">Comparable scores · out of {number.format(data.maximum)} marks</p><p>{data.selectedRoundId ? "Only teams that completed the selected review contribute to score statistics." : "Only teams that completed every review round contribute to overall score statistics."} Pending reviews are not counted as zero. Small samples or differences in judging can affect results; these numbers alone do not establish problem difficulty.</p></div>
    <section className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs">
      <caption className="sr-only">Problem statement performance with completed-review score samples and progress for each round.</caption>
      <thead className="border-b border-zinc-200 bg-zinc-50 text-[11px] text-zinc-500"><tr><th scope="col" className="px-4 py-3">Problem statement</th><th scope="col" className="px-3 py-3 text-right">Teams</th><th scope="col" className="px-3 py-3 text-right">Scored sample</th><th scope="col" className="px-3 py-3 text-right">Average</th><th scope="col" className="px-3 py-3 text-right">Highest</th><th scope="col" className="px-3 py-3 text-right">Lowest</th>{data.rounds.map((round) => <th key={round.id} scope="col" className="min-w-32 px-3 py-3">Review {round.number}</th>)}<th scope="col" className="px-4 py-3">Completion</th></tr></thead>
      <tbody className="divide-y divide-zinc-100">{data.rows.map((row) => <tr key={row.id} className="transition-colors hover:bg-zinc-50/70"><th scope="row" className="max-w-72 px-4 py-4 text-left font-normal"><Link href={`/admin/leaderboard?problem=${encodeURIComponent(row.id)}`} className="font-mono font-semibold text-blue-700 hover:underline">{row.code}</Link><p className="mt-1 text-zinc-600">{row.title}</p></th><td className="px-3 py-4 text-right tabular-nums">{row.teamCount}</td><td className="px-3 py-4 text-right tabular-nums text-zinc-500">{row.sampleSize} / {row.teamCount}</td><td className="px-3 py-4 text-right font-semibold tabular-nums">{score(row.average)}</td><td className="px-3 py-4 text-right tabular-nums">{score(row.highest)}</td><td className="px-3 py-4 text-right tabular-nums">{score(row.lowest)}</td>{row.progress.map((round) => <td key={round.id} className="px-3 py-4"><p className={round.completed ? "font-medium text-emerald-700" : "text-zinc-500"}>{round.completed} / {row.teamCount} done</p><p className="mt-1 text-[10px] text-zinc-500"><span className={round.inProgress ? "text-amber-700" : ""}>{round.inProgress} active</span> · {round.pending} pending</p></td>)}<td className="min-w-32 px-4 py-4"><p className="font-medium tabular-nums">{row.totalReviews ? `${row.completionPercentage}%` : "—"}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-zinc-100" aria-hidden="true"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${row.completionPercentage}%` }} /></div><p className="mt-1 text-[10px] text-zinc-400">{row.completedReviews} / {row.totalReviews} reviews</p></td></tr>)}</tbody>
    </table></div>{!data.rows.length ? <p className="p-10 text-center text-sm text-zinc-500">No problem statements available yet.</p> : null}</section>
    <p className="text-xs text-zinc-400">Statistics follow assigned problem statements even if a team moves venue. Refresh to load the latest submitted reviews.</p>
  </div>;
}
