import "server-only";
import { AnnouncementAudience, IssueCategory, IssueStatus, SubmissionType } from "@/generated/prisma/client";
import { getDb } from "@/lib/db";

async function currentHackathon() { return (await getDb().hackathon.findFirst({ where: { status: "LIVE" }, orderBy: { startDate: "desc" } })) ?? getDb().hackathon.findFirst({ orderBy: { startDate: "desc" } }); }

export async function getReviewReleaseSettings() { const event = await currentHackathon(); if (!event) return []; return getDb().reviewRound.findMany({ where: { hackathonId: event.id }, orderBy: { displayOrder: "asc" }, select: { id: true, roundNumber: true, name: true, feedbackVisibleToTeams: true } }); }
export async function setFeedbackVisibility(roundId: string, visible: boolean) { const event = await currentHackathon(); if (!event) return false; const result = await getDb().reviewRound.updateMany({ where: { id: roundId, hackathonId: event.id }, data: { feedbackVisibleToTeams: visible } }); return result.count === 1; }

export const standardSubmissionTypes = [SubmissionType.GITHUB, SubmissionType.PRESENTATION, SubmissionType.DEMO, SubmissionType.PROTOTYPE, SubmissionType.VIDEO, SubmissionType.DOCUMENTATION] as const;
export async function getSubmissionOverview() { const event = await currentHackathon(); if (!event) return []; const teams = await getDb().team.findMany({ where: { hackathonId: event.id }, include: { venue: true, submissions: true }, orderBy: { teamCode: "asc" } }); return teams.map((team) => ({ id: team.id, code: team.teamCode, name: team.teamName, venue: team.venue.name, submitted: new Set(team.submissions.map((item) => item.type)) })); }

export async function getAdminAnnouncements() { const event = await currentHackathon(); if (!event) return { venues: [], announcements: [] }; const [venues, announcements] = await Promise.all([getDb().venue.findMany({ where: { hackathonId: event.id }, orderBy: { displayOrder: "asc" }, select: { id: true, name: true, roomNumber: true } }), getDb().announcement.findMany({ where: { hackathonId: event.id }, include: { venue: true }, orderBy: [{ publishedAt: "desc" }, { createdAt: "desc" }] })]); return { venues, announcements }; }
export async function createAnnouncement(input: { title: string; message: string; audience: string; venueId?: string; expiresAt?: string }) { const event = await currentHackathon(); if (!event || !Object.values(AnnouncementAudience).includes(input.audience as AnnouncementAudience) || input.title.trim().length < 3 || input.title.trim().length > 120 || input.message.trim().length < 3 || input.message.trim().length > 3000) return false; const audience = input.audience as AnnouncementAudience; const venueId = audience === AnnouncementAudience.VENUE ? input.venueId : null; if (audience === AnnouncementAudience.VENUE && !venueId) return false; if (venueId && !(await getDb().venue.findFirst({ where: { id: venueId, hackathonId: event.id }, select: { id: true } }))) return false; const expiresAt = input.expiresAt ? new Date(input.expiresAt) : null; if (expiresAt && Number.isNaN(expiresAt.valueOf())) return false; await getDb().announcement.create({ data: { id: crypto.randomUUID(), hackathonId: event.id, title: input.title.trim(), message: input.message.trim(), audience, venueId, expiresAt } }); return true; }
export async function editAnnouncement(input: { id: string; title: string; message: string; audience: string; venueId?: string; expiresAt?: string }) { const event = await currentHackathon(); if (!event || !Object.values(AnnouncementAudience).includes(input.audience as AnnouncementAudience) || input.title.trim().length < 3 || input.title.trim().length > 120 || input.message.trim().length < 3 || input.message.trim().length > 3000) return false; const audience = input.audience as AnnouncementAudience; const venueId = audience === AnnouncementAudience.VENUE ? input.venueId : null; if (audience === AnnouncementAudience.VENUE && !venueId) return false; if (venueId && !(await getDb().venue.findFirst({ where: { id: venueId, hackathonId: event.id }, select: { id: true } }))) return false; const expiresAt = input.expiresAt ? new Date(input.expiresAt) : null; if (expiresAt && Number.isNaN(expiresAt.valueOf())) return false; const result = await getDb().announcement.updateMany({ where: { id: input.id, hackathonId: event.id }, data: { title: input.title.trim(), message: input.message.trim(), audience, venueId, expiresAt } }); return result.count === 1; }
export async function updateAnnouncementState(id: string, action: string) { const event = await currentHackathon(); if (!event) return false; if (action === "delete") return (await getDb().announcement.deleteMany({ where: { id, hackathonId: event.id } })).count === 1; const current = await getDb().announcement.findFirst({ where: { id, hackathonId: event.id }, select: { publishedAt: true } }); if (!current) return false; await getDb().announcement.update({ where: { id }, data: { publishedAt: action === "publish" ? new Date() : null } }); return true; }

export async function getAdminIssues(filters: { status?: string; category?: string; venueId?: string } = {}) { const event = await currentHackathon(); if (!event) return { venues: [], issues: [] }; const status = Object.values(IssueStatus).includes(filters.status as IssueStatus) ? filters.status as IssueStatus : undefined; const category = Object.values(IssueCategory).includes(filters.category as IssueCategory) ? filters.category as IssueCategory : undefined; const [venues, rows] = await Promise.all([getDb().venue.findMany({ where: { hackathonId: event.id }, orderBy: { displayOrder: "asc" }, select: { id: true, name: true } }), getDb().teamIssue.findMany({ where: { team: { hackathonId: event.id, ...(filters.venueId ? { venueId: filters.venueId } : {}) }, ...(status ? { status } : {}), ...(category ? { category } : {}) }, include: { team: { include: { venue: true } } }, orderBy: { createdAt: "desc" } })]); const timestamp = Date.now(); return { venues, issues: rows.map((issue) => ({ ...issue, ageMinutes: Math.max(0, Math.floor((timestamp - issue.createdAt.getTime()) / 60000)) })) }; }
export async function updateIssue(input: { id: string; status: string; response: string }) { if (!Object.values(IssueStatus).includes(input.status as IssueStatus) || input.response.length > 3000) return false; const event = await currentHackathon(); if (!event) return false; const current = await getDb().teamIssue.findFirst({ where: { id: input.id, team: { hackathonId: event.id } }, select: { id: true } }); if (!current) return false; const status = input.status as IssueStatus; await getDb().teamIssue.update({ where: { id: current.id }, data: { status, adminResponse: input.response.trim() || null, resolvedAt: status === IssueStatus.RESOLVED || status === IssueStatus.CLOSED ? new Date() : null } }); return true; }
export async function getAdminIssueSummary() { const event = await currentHackathon(); if (!event) return { open: 0, oldestMinutes: 0 }; const issues = await getDb().teamIssue.findMany({ where: { team: { hackathonId: event.id }, status: { in: [IssueStatus.OPEN, IssueStatus.IN_PROGRESS] } }, select: { createdAt: true }, orderBy: { createdAt: "asc" } }); return { open: issues.length, oldestMinutes: issues[0] ? Math.max(0, Math.floor((Date.now() - issues[0].createdAt.getTime()) / 60000)) : 0 }; }

export { AnnouncementAudience, IssueCategory, IssueStatus, SubmissionType };
