import { Bell, ChevronDown } from "lucide-react";
import { formatDateTime } from "@/lib/format";
import { getTeamPortalData } from "@/lib/repositories/team-repository";
import { requireTeamSession } from "@/lib/require-team-session";

export default async function TeamAnnouncementsPage() {
  const data = await getTeamPortalData(await requireTeamSession());
  if (!data) return null;
  return <div className="space-y-5"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold text-blue-700">Event updates</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Announcements</h1><p className="mt-1 text-sm text-zinc-500">Event-wide and venue-specific notices for your team.</p></div><span className="text-xs text-zinc-500">{data.announcements.length} active</span></div>{data.announcements.length ? <div className="space-y-3">{data.announcements.map((item, index) => <details key={item.id} open={index === 0} className="group overflow-hidden rounded-xl border border-zinc-200 bg-white transition-all duration-200 open:border-zinc-300 open:shadow-sm"><summary className="flex cursor-pointer list-none items-start gap-3 p-4 sm:p-5"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-blue-100 bg-blue-50"><Bell className="size-4 text-blue-700" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold text-zinc-900">{item.title}</h2><span className="rounded border border-zinc-200 bg-zinc-50 px-1.5 py-0.5 text-[9px] font-semibold text-zinc-500">{item.audience}</span></div><p className="mt-1 text-xs text-zinc-400">{formatDateTime(item.publishedAt)}</p></div><ChevronDown className="mt-1 size-4 shrink-0 text-zinc-400 transition-transform duration-200 group-open:rotate-180" /></summary><p className="border-t border-zinc-100 bg-zinc-50/50 px-4 py-4 text-sm leading-7 text-zinc-600 sm:px-5">{item.message}</p></details>)}</div> : <div className="rounded-xl border border-dashed border-zinc-300 bg-white p-8 text-center"><Bell className="mx-auto size-5 text-zinc-400" /><p className="mt-2 text-sm font-medium text-zinc-700">No active announcements</p><p className="mt-1 text-xs text-zinc-500">New event notices will appear here.</p></div>}</div>;
}
