import Link from "next/link";
import { ArrowRight, Bell, Building2, CheckCircle2, Clock3, Link2, MapPin, MessageSquareWarning, Target, Users } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDateTime } from "@/lib/format";
import { getTeamPortalData, submissionTypes } from "@/lib/repositories/team-repository";
import { requireTeamSession } from "@/lib/require-team-session";

export default async function TeamHomePage() {
  const data = await getTeamPortalData(await requireTeamSession());
  if (!data) return null;
  const latestFeedback = data.rounds.findLast((round) => round.feedback);
  const openIssues = data.issues.filter((issue) => issue.status === "OPEN" || issue.status === "IN_PROGRESS");
  const completedReviews = data.rounds.filter((round) => round.status === "completed").length;

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-xl border border-zinc-200 bg-white">
      <div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(250px,0.75fr)]">
        <div><div className="flex flex-wrap items-center gap-2"><span className="rounded-md border border-blue-200 bg-blue-50 px-2 py-1 font-mono text-xs font-semibold text-blue-700">{data.identity.code}</span><span className="inline-flex items-center gap-1.5 text-xs text-zinc-500"><MapPin className="size-3.5" />{data.venue.name} · {data.venue.room}</span></div><h1 className="mt-3 text-2xl font-semibold tracking-tight text-zinc-950 sm:text-3xl">{data.identity.name}</h1><p className="mt-1.5 text-sm text-zinc-500">Your operational workspace for the internal hackathon.</p></div>
        <div className="grid grid-cols-3 overflow-hidden rounded-lg border border-zinc-200 bg-zinc-50/60"><div className="p-3 text-center"><p className="text-xl font-semibold tabular-nums">{completedReviews}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-zinc-500">Reviews</p></div><div className="border-x border-zinc-200 p-3 text-center"><p className="text-xl font-semibold tabular-nums">{data.submissions.length}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-zinc-500">Links</p></div><div className="p-3 text-center"><p className="text-xl font-semibold tabular-nums">{openIssues.length}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-zinc-500">Issues</p></div></div>
      </div>
      <div className="border-t border-zinc-100 bg-zinc-50/50 px-5 py-3 text-xs text-zinc-500 sm:px-6"><span className="font-medium text-zinc-700">{data.problem.code}</span> · {data.problem.title}</div>
    </section>

    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,0.65fr)]">
      <div className="space-y-6">
        <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold text-zinc-900">Evaluation timeline</h2><Link href="/team/reviews" className="inline-flex items-center gap-1 text-xs font-medium text-blue-700 hover:text-blue-800">View feedback <ArrowRight className="size-3.5" /></Link></div><div className="divide-y divide-zinc-100 rounded-xl border border-zinc-200 bg-white">
          {data.rounds.map((round) => <div key={round.id} className="group flex items-center gap-3 p-4 transition-colors hover:bg-zinc-50/70"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-zinc-50 text-xs font-semibold text-zinc-600">R{round.number}</div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-zinc-900">{round.name}</p><p className="mt-0.5 flex items-center gap-1 text-xs text-zinc-500">{round.completedAt ? <><Clock3 className="size-3" /> Completed {formatDateTime(round.completedAt)}</> : round.startedAt ? <><Clock3 className="size-3" /> Started {formatDateTime(round.startedAt)}</> : "Waiting to begin"}</p></div><StatusBadge status={round.status} compact /></div>)}
        </div></section>

        <section className="rounded-xl border border-zinc-200 bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-zinc-50"><Target className="size-4 text-zinc-600" /></div><div><p className="font-mono text-xs font-semibold text-blue-700">{data.problem.code}</p><h2 className="mt-1 text-lg font-semibold text-zinc-950">{data.problem.title}</h2></div></div><p className="mt-4 text-sm leading-7 text-zinc-600">{data.problem.description}</p><dl className="mt-5 grid gap-3 border-t border-zinc-100 pt-4 sm:grid-cols-2"><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-zinc-400">Organization</dt><dd className="mt-1 text-sm font-medium text-zinc-700">{data.problem.organization}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-zinc-400">Theme</dt><dd className="mt-1 text-sm font-medium text-zinc-700">{data.problem.theme}</dd></div></dl></section>

        <section><div className="mb-2 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold text-zinc-900"><Users className="size-4 text-zinc-500" /> Team members</h2><span className="text-xs text-zinc-500">{data.members.length} registered</span></div><div className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="hidden grid-cols-[1.2fr_1fr_90px_100px] gap-3 border-b border-zinc-200 bg-zinc-50 px-4 py-2.5 text-[11px] font-semibold uppercase tracking-wide text-zinc-500 sm:grid"><span>Name</span><span>Roll / department</span><span>Year</span><span>Role</span></div>{data.members.map((member) => <div key={member.id} className="grid gap-1 border-b border-zinc-100 px-4 py-3.5 last:border-0 sm:grid-cols-[1.2fr_1fr_90px_100px] sm:items-center sm:gap-3"><p className="text-sm font-medium text-zinc-900">{member.name}</p><p className="text-xs text-zinc-500">{member.rollNumber} · {member.department}</p><p className="text-xs text-zinc-500">Year {member.year}</p><p className="text-xs font-medium text-zinc-600">{member.role}</p></div>)}</div></section>
      </div>

      <aside className="space-y-4">
        <Link href="/team/submissions" className="group block rounded-xl border border-zinc-200 bg-white p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-zinc-300 hover:shadow-sm"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><Link2 className="size-4" /> Submission readiness</span><ArrowRight className="size-4 text-zinc-300 transition-transform group-hover:translate-x-0.5" /></div><p className="mt-3 text-2xl font-semibold tabular-nums">{data.submissions.length} <span className="text-sm font-normal text-zinc-400">/ {submissionTypes.length}</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-blue-600 transition-[width] duration-500" style={{ width: `${Math.round(data.submissions.length / submissionTypes.length * 100)}%` }} /></div><p className="mt-2 text-xs text-zinc-500">project resources linked</p></Link>
        <Link href="/team/issues" className="group block rounded-xl border border-zinc-200 bg-white p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-zinc-300 hover:shadow-sm"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><MessageSquareWarning className="size-4" /> Support desk</span><ArrowRight className="size-4 text-zinc-300 transition-transform group-hover:translate-x-0.5" /></div><p className="mt-3 text-sm font-semibold text-zinc-900">{openIssues.length ? `${openIssues.length} issue${openIssues.length === 1 ? "" : "s"} need attention` : "No open issues"}</p><p className="mt-1 text-xs text-zinc-500">Faculty responses appear here.</p></Link>
        {latestFeedback ? <Link href="/team/reviews" className="group block rounded-xl border border-emerald-200 bg-emerald-50/60 p-4 transition-all duration-200 hover:-translate-y-0.5"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-700"><CheckCircle2 className="size-4" /> Latest released feedback</div><p className="mt-3 line-clamp-3 text-sm leading-6 text-emerald-950/75">{latestFeedback.feedback?.remarks}</p>{latestFeedback.feedback?.submittedAt ? <p className="mt-2 text-xs text-emerald-700/70">{formatDateTime(latestFeedback.feedback.submittedAt)}</p> : null}</Link> : null}
        {data.announcements[0] ? <Link href="/team/announcements" className="group block rounded-xl border border-zinc-200 bg-white p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-zinc-300 hover:shadow-sm"><div className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><Bell className="size-4" /> Latest announcement</div><p className="mt-3 text-sm font-semibold text-zinc-900">{data.announcements[0].title}</p><p className="mt-1 line-clamp-3 text-sm leading-6 text-zinc-600">{data.announcements[0].message}</p></Link> : null}
        <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-4"><p className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><Building2 className="size-4" /> Assigned location</p><p className="mt-3 text-sm font-semibold text-zinc-900">{data.venue.name}</p><p className="mt-1 text-xs text-zinc-500">Room {data.venue.room}</p></div>
      </aside>
    </div>
  </div>;
}
