import { Bell, MapPin, MessageSquareWarning, Users } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { getTeamPortalData, submissionTypes } from "@/lib/repositories/team-repository";
import { requireTeamSession } from "@/lib/require-team-session";
import { formatDateTime } from "@/lib/format";

export default async function TeamHomePage() { const data = await getTeamPortalData(await requireTeamSession()); if (!data) return null; const latestFeedback = data.rounds.findLast((r) => r.feedback); const openIssues = data.issues.filter((i) => i.status === "OPEN" || i.status === "IN_PROGRESS"); return <div className="space-y-5">
  <section className="rounded-xl border border-zinc-200 bg-white p-4 sm:p-5"><p className="font-mono text-xs font-semibold text-blue-700">{data.identity.code}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">{data.identity.name}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-zinc-500"><MapPin className="size-3.5" /> {data.venue.name} · {data.venue.room}</p><div className="mt-4 border-t border-zinc-100 pt-4"><p className="text-xs font-semibold text-zinc-500">{data.problem.code}</p><p className="mt-1 text-sm font-medium text-zinc-900">{data.problem.title}</p></div></section>
  <section><h2 className="mb-2 text-sm font-semibold">Current evaluation status</h2><div className="divide-y divide-zinc-100 rounded-xl border border-zinc-200 bg-white">{data.rounds.map((round) => <div key={round.id} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">Review {round.number}</p><p className="mt-0.5 text-xs text-zinc-500">{round.name}</p></div><StatusBadge status={round.status} compact /></div>)}</div></section>
  <div className="grid gap-4 sm:grid-cols-2"><section className="rounded-xl border border-zinc-200 bg-white p-4"><p className="text-xs font-semibold text-zinc-500">Latest feedback</p><p className="mt-2 text-sm leading-6 text-zinc-700">{latestFeedback?.feedback?.remarks || "No released feedback yet."}</p>{latestFeedback?.feedback?.submittedAt ? <p className="mt-2 text-xs text-zinc-400">{formatDateTime(latestFeedback.feedback.submittedAt)}</p> : null}</section><section className="rounded-xl border border-zinc-200 bg-white p-4"><p className="text-xs font-semibold text-zinc-500">Submission status</p><p className="mt-2 text-2xl font-semibold">{data.submissions.length} / {submissionTypes.length}</p><p className="mt-1 text-xs text-zinc-500">project links submitted</p></section></div>
  {data.announcements[0] ? <section className="rounded-xl border border-zinc-200 bg-white p-4"><div className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><Bell className="size-3.5" /> Latest announcement</div><p className="mt-2 text-sm font-semibold">{data.announcements[0].title}</p><p className="mt-1 text-sm leading-6 text-zinc-600">{data.announcements[0].message}</p></section> : null}
  <div className="grid gap-4 sm:grid-cols-2"><section className="rounded-xl border border-zinc-200 bg-white p-4"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><MessageSquareWarning className="size-3.5" /> Open issues</p><span className="text-sm font-semibold">{openIssues.length}</span></div></section><section className="rounded-xl border border-zinc-200 bg-white p-4"><p className="flex items-center gap-2 text-xs font-semibold text-zinc-500"><Users className="size-3.5" /> Team members</p><p className="mt-2 text-sm font-semibold">{data.members.length} registered members</p></section></div>
  <details className="group rounded-xl border border-zinc-200 bg-white"><summary className="cursor-pointer list-none p-4 text-sm font-semibold">Team & problem details</summary><div className="space-y-4 border-t border-zinc-100 p-4"><p className="text-sm leading-6 text-zinc-600">{data.problem.description}</p><div className="divide-y divide-zinc-100">{data.members.map((m) => <div key={m.id} className="flex justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{m.name}</p><p className="text-xs text-zinc-500">{m.rollNumber} · {m.department} · Year {m.year}</p></div><span className="text-xs text-zinc-500">{m.role}</span></div>)}</div></div></details>
</div>; }
